### ISSUE TITLE
BUG Crash

### ISSUE THREAD

**Issue by Heitortadeu** [Ezzz-dev/Nostalrius#64]
We have a bug on this base that causes it to crash. The same was fixed in TFS, however the commit is different from the applications that can be applied here in the base.

Here's a reported bug:
https://otland.net/threads/gdb-error-crash.274852/#post-2646765

Commitment Follows FIX:
https://github.com/otland/forgottenserver/commit/b18cf9ff8da9b83b1ca3e99ea5d4b83496d59227

**Comment by tarantonio** [comment]
How can I reproduce the bug?
My working server don't have that crash at the moment.

**Comment by Heitortadeu** [comment]
> How can I reproduce the bug? Do you use the repo as it is or you made modifications?
> My working server don't have that crash at the moment.

my server is uniquely this one, without modification!
my server started to go down after months online..
apparently it has to do with some timer.
it seems to me that the bug has been with the TFS fix I posted above.

**Comment by tysonstrange** [comment]
Are you still having this crash? I've not seen it occur.

**Comment by tysonstrange** [comment]
I dont think this crash or this fix posted are related.

The fix posted relates to a bug that was introducted when moving from the Scheduler to boost::asio 

The fix was changing the code for the boost::asio method, this scheduler is using a lock and shouldn't be related to this.
